CONFIDENCE_LEVEL: 0.95
FETCH_BATCH_SIZE: 20
FETCH_INTERVAL: 300
FETCH_TIMEOUT: 10
INITIAL_SCORE: 10
MAX_FETCHERS: 5
MAX_RETRY_TIMES: 3
MAX_SCORE: 100
MIN_SAMPLE_SIZE: 10
MIN_SCORE: 0
REDIS_DB: 0
REDIS_HOST: localhost
REDIS_KEY: proxies
REDIS_PASSWORD: null
REDIS_PORT: 6379
SAMPLE_SIZE: 50
SCORE_STEP: 1
TEST_URLS:
- http://www.baidu.com
VALIDATE_BATCH_SIZE: 100
VALIDATE_INTERVAL: 300
VALIDATE_TIMEOUT: 5
